### ISSUE TITLE
Add a daemon mode

### ISSUE THREAD

**Issue by raphink** [camptocamp/bivac#106]
Make conplicity work as a daemon with an infinite loop, passing it a schedule (cron-style) for backups, e.g.:

``` shell
$ conplicity --schedule "0 3 * * *"
```

This would also allow to override these schedules per volume, using labels/config files:

``` shell
# Backup this volume at 4:42AM
io.conplicity.schedule="42 4 * * *"
```

Conplicity would then parse these information during a first run, and get in daemon mode afterwards, planning its runs accordingly.

**Comment by mcanevet** [comment]
Fix in v2
