### ISSUE TITLE
How do you do a restore

### ISSUE THREAD

**Issue by Vad1mo** [camptocamp/bivac#118]
I would like to perform an automatic restore when on start the backup source directory is empty. 

Or more in general how can perform a restore with conplicity.

**Comment by mcanevet** [comment]
@Vad1mo you should use `duplicity` to restore a backup.
As this is a on-demand thing for us, we didn't implement any automated thing to do it, but if you have any workflow requiring an automated restore, we'd gladly merge a PR allowing to do it.

**Comment by mcanevet** [comment]
Actually since Bivac v2 we should be able to add restore feature. I re-open this issue.

**Comment by codejamninja** [comment]
Restore is in alpha stage in the following pull request.

https://github.com/camptocamp/bivac/pull/273

**Comment by cryptobioz** [comment]
The PR has been merged, this feature will be available in the next release (v2.1). The documentation is available here : https://github.com/camptocamp/bivac/wiki/Usage#restore-a-volume
