### ISSUE TITLE
support path style syntax for s3 compatible storages

### ISSUE THREAD

**Issue by mgolisch** [camptocamp/bivac#126]
We use minio in our datacenter for s3 compatible stoage.
Unfortunately it doesnt support the new virtual-host style syntax for buckets.
Would be nice if there was an option in conplicity to not pass --s3-use-new-style to duplicity.
So i wouldnt need to fish that out again in my custom duplicity image.

**Comment by raphink** [comment]
I'd definitely welcome a pr for that!

**Comment by mcanevet** [comment]
@mgolisch did you try with `restic` engine? I think that it should work.

**Comment by mcanevet** [comment]
@mgolisch actually I think that it already works even with `duplicity` engine.
We are using it with an s3-like service using an url in that format:
`s3://<host>/<bucket>`.
I close this for now. Feel free to reopen if you still have issues.
