### ISSUE TITLE
"Backup dir" environment variable for volumes

### ISSUE THREAD

**Issue by MorbZ** [camptocamp/bivac#130]
Please add an environment variable for volumes that restricts the backed up data to a subdirectory of this volume. It should by similar to the `GetBackupDir()` function of the provider interface.

The reason behind this is that it would let me run a cron job that backs up a database (in my case InfluxDB) which hasn't already a provider in conplicity. 

Example:
To only backup the "backups" directory of the volume:
`io.conplicity.backup_dir=backups`

**Comment by raphink** [comment]
That sounds like a good idea. I'd welcome a PR for that.

**Comment by mcanevet** [comment]
@MorbZ writing an InfluxDB provider should be quite easy I think.

**Comment by mcanevet** [comment]
@MorbZ providers can now be configured at runtime, so I close this issue for now.
Feel free to reopen if it does not solve your use case.
