### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mcanevet** [camptocamp/bivac#170]

**Comment by raphink** [comment]
We essentially have 3 ways (4 when #172 is merged) to install and run Bivac at the moment:

* local install (curl or go get/build) + local run
* Docker (image pull + run)
* K8s (helm)

So we should adapt documentation so users can choose the way they want to install and run, and get instructions accordingly.

The rest of the doc (vocab, contrib) is common.

**Comment by dhilgarth** [comment]
I would also love to see an explanation of the backup itself, even high level.
Currently, in the repo it says that it backs up via Restic. On the [website](https://camptocamp.github.io/bivac/) it says that it supports Restic, RClone and Duplicity. Are they used together? If yes, how? If not, how to choose which one to use?

**Comment by mcanevet** [comment]
RClone and Duplicity are not supported anymore in v2.
Documentation really needs some love...

**Comment by dhilgarth** [comment]
Good to know :) Also, it's unclear how to actually use the bivac docker image. Simply starting it just prints the usage.
Starting it with `manager -v` - which I found in one issue here - will print a lot of messages regarding volumes being backed up, but no data will actually appear in my Azure Storage. But no error message in the bivac output either. So, how to actually send the backup to the remote location?

**Comment by dhilgarth** [comment]
Is Prometheus still supported? If so, how? An example would be helpful :-)

**Comment by mcanevet** [comment]
I think the only thing left to document is the embedded Prometheus exporter.

**Comment by mcanevet** [comment]
Actually, the documentation exists : https://github.com/camptocamp/bivac/wiki/Monitoring
