### ISSUE TITLE
Feature request: webbooks

### ISSUE THREAD

**Issue by lukasmrtvy** [camptocamp/bivac#211]
- Trigger custom webhook based on return code. 
- Payload can be a log from backup output

It can be used for future Teams/Slack notifications

**Comment by mcanevet** [comment]
@lukasmrtvy I think the better way to deal with this use case is to use Prometheus+Alertmanager to send notifications.
As Bivac v2 has an embedded Prometheus exporter, this is already possible.
I'll close this issue as we don't plan to implement further webhook/payload system.

**Comment by lukasmrtvy** [comment]
@mcanevet 
Point was to integrate https://healthchecks.io/ as proactive monitoring, instead of reactive monitoring with Prometheus+Alertmanager.
