### ISSUE TITLE
Feature request: Use backend option from rclone

### ISSUE THREAD

**Issue by lukasmrtvy** [camptocamp/bivac#213]
It would be a great if you can use backends from rclone.

For example:
- use restic for backup
- use rclone google drive as backend for restic

These two tools can play nice with each other
https://restic.net/blog/2018-04-01/rclone-backend

**Comment by mcanevet** [comment]
@lukasmrtvy I'm wondering if it's not already possible. What you need is a special image containing both `restic` and `rclone` binary, then with `--extra-env` you may be able to configure both programs to make them work together.

**Comment by lukasmrtvy** [comment]
Maye would be better to have `--extra-env`  for/under Restic Options and  `--extra-env` for/under RClone Options, etc. Because You can have variables with same name for different images.

> I did rclone image with backend serving https://github.com/lukasmrtvy/docker-rclone/

This may works:
```
--restic-image=restic/restic \
--extra-env="RESTIC_REPOSITORY=rest:https://user:verysecret@rclone/ RCLONE_BACKEND_PROTOCOL='restic' RCLONE_BACKEND='myremote' RCLONE_BACKEND_PATH='/backup' RCLONE_BACKEND_PASS='verysecret' RCLONE_BACKEND_USER='user'
--rclone-image lukasmrtvy/rclone \
```

, but there is a problem with special backend type like Google Drive, cuz you need to do oauth and store token and configurations (Not possible to store credentials in env variables) . So basically rclone needs volume for static files.

Is there any argument which can override rclone/rclone/duplicity docker run arguments?

For example
```
--restic-docker-extra-args=
--rclone-docker-extra-args=" -v rclone_volume:/opt/rclone/conf"
```

Thanks

**Comment by mcanevet** [comment]
We definitely need to find a way to pass arbitrary arguments to worker.

**Comment by lukasmrtvy** [comment]
@mcanevet:
rclone as backend would cover most storage options.

Rclone can be backend (https://restic.net/blog/2018-04-01/rclone-backend) for Restic and Duplicity (https://github.com/GilGalaad/duplicity-rclone) and of course for itsefl.

So something like:
```
RClone Options:
      --rclone-args=                      Arguments to pass to rclone engine. [$RCLONE_COMMON_ARGS]
      --rclone-backup-args=               Arguments to pass to rclone engine when backup. (default: %D %B/%P/%V) [$RCLONE_BACKUP_ARGS]
      --rclone-image=                     The rclone docker image. (default: camptocamp/rclone:1.42-1) [$RCLONE_DOCKER_IMAGE]
RClone backend Options:
      --rclone-image="lukasmrtvy/docker-rclone:latest"
      --rclone-backend=true  
      --rclone-backend-args="RCLONE_BACKEND_PROTOCOL=restic -e RCLONE_BACKEND=myremote -e RCLONE_BACKEND_PATH=/backup RCLONE_BACKEND_ADDR=0.0.0.0:8080  RCLONE_BACKEND_USER=foo RCLONE_BACKEND_PASS=bar"
      --rclone-backend-pass-args-to-engine="ENGINE_BACKEND=127.0.0.1:8080 ENGINE_USER=foo ENGINE_PASS=bar "
```

How to create Rclone config? (For example: interactive Google Drive login with oauth2)

```
docker run --rm -it -v rclone_data:/home/rclone/.config/rclone -e CONFIG_CREATE="True" lukasmrtvy/docker-rclone:latest /opt/rclone/rclone config
```

or

```
docker run --rm -it --network host -v rclone_data:/home/rclone/.config/rclone -e CONFIG_CREATE="True" lukasmrtvy/docker-rclone:latest /opt/rclone/rclone config create myremote drive root_folder_id "1Aw9xxxxxxxxxxxxxxxxxxxxx_Hmg"
```

Think about it. Rclone has huge amout of backend options. S3 is not enough :)
