### ISSUE TITLE
configure Bivac to use cattle ?

### ISSUE THREAD

**Issue by jeanpommier** [camptocamp/bivac#245]
Hi,
I'm trying to use Bivac with Cattle. It seems I can't make it work. I have first tried using docker, it works like a charm. But using cattle orchestrator, I get very dry log message and then nothing. The S3 bucket stays empty.
The logs : 

> 16/11/2018 15:32:22time="2018-11-16T14:32:22Z" level=info msg="Bivac v starting backup..."
16/11/2018 15:32:22time="2018-11-16T14:32:22Z" level=debug msg="Choosing orchestrator based on configuration..."
16/11/2018 15:32:22time="2018-11-16T14:32:22Z" level=debug msg="Using orchestrator: Cattle"
16/11/2018 15:32:22time="2018-11-16T14:32:22Z" level=info msg="End backup..."

Here is my compose file (I truncated the keys.
[docker-compose.txt](https://github.com/camptocamp/bivac/files/2589648/docker-compose.txt)
As for the cattle url, I've tried the v1 api url, the v2-beta, no api slug, with no difference
Is this a bug or I am doing something wrong ?

I'm using Rancher 1.6.22 with Cattle orchestrator

**Comment by raphink** [comment]
The easiest way to use Bivac with cattle is to add [Camptocamp's catalog](https://github.com/camptocamp/camptocamp-rancher-catalog) to your Rancher server.

You will then have a Bivac catalog entry which configures it properly: https://github.com/camptocamp/camptocamp-rancher-catalog/blob/master/templates/bivac/11/docker-compose.yml

**Comment by jeanpommier** [comment]
Well, actually, that's what I did (I cleaned up a bit the compose file afterward, but direct from the catalog is no better.

**Comment by cryptobioz** [comment]
@jeanpommier Bivac does not find any volume. Are you able to list your volumes using the API: [https://[RANCHER-SERVER]/v2-beta/projects/[RANCHER-ENV]/volumes]() ?

**Comment by jeanpommier** [comment]
Hi,
Thanks for answering. 
Yes, I can list them using the API. do you want to inspect the output ? I can PM it to you if necessary 
Here is an extract corresponding to the geonetwork_datadir volume:

> {
> 
>     "id": "1v4736",
>     "type": "volume",
>     "links": {
>         "self": "…/v2-beta/projects/1a5/volumes/1v4736",
>         "account": "…/v2-beta/projects/1a5/volumes/1v4736/account",
>         "backups": "…/v2-beta/projects/1a5/volumes/1v4736/backups",
>         "mounts": "…/v2-beta/projects/1a5/volumes/1v4736/mounts",
>         "snapshots": "…/v2-beta/projects/1a5/volumes/1v4736/snapshots",
>         "storagePools": "…/v2-beta/projects/1a5/volumes/1v4736/storagepools"
>     },
>     "actions": {
>         "deallocate": "…/v2-beta/projects/1a5/volumes/1v4736/?action=deallocate",
>         "update": "…/v2-beta/projects/1a5/volumes/1v4736/?action=update"
>     },
>     "baseType": "volume",
>     "name": "geonetwork_datadir",
>     "state": "active",
>     "accessMode": null,
>     "accountId": "1a5",
>     "created": "2018-10-09T19:33:21Z",
>     "createdTS": 1539113601000,
>     "description": "environment-scoped volume created with terraform",
>     "driver": "local",
>     "driverOpts": null,
>     "externalId": "geonetwork_datadir",
>     "hostId": null,
>     "imageId": null,
>     "instanceId": null,
>     "isHostPath": false,
>     "kind": "volume",
>     "mounts": [
>         {
>             "type": "mountEntry",
>             "volumeName": "geonetwork_datadir",
>             "instanceName": "georchestra-geonetwork-1",
>             "path": "/mnt/geonetwork_datadir",
>             "permission": "rw",
>             "instanceId": "1i2305",
>             "volumeId": "1v4736"
>         }
>     ],
>     "removed": null,
>     "sizeMb": null,
>     "stackId": null,
>     "storageDriverId": null,
>     "transitioning": "no",
>     "transitioningMessage": null,
>     "transitioningProgress": null,
>     "uri": "local:///geonetwork_datadir",
>     "uuid": "cf227dd8-0561-4e00-bc3c-abd3166239fc",
>     "volumeTemplateId": null
> 
> }

**Comment by cryptobioz** [comment]
Everything looks good on the API side. Are you using an "account API key" or an "environment API key"? Cattle is supposed to dynamically create API keys for the service, did you try to start Bivac without providing the CATTLE_* environment variables?

**Comment by jeanpommier** [comment]
Hi,
It's an environment API key.
I've tried recreating the bivac stack from scratch using the C2C catalog, without setting the API keys, as you suggested. No difference.

**Comment by cryptobioz** [comment]
Did you create the stack as a system stack? Could you try to run Bivac with account API keys?

**Comment by jeanpommier** [comment]
Nope, I used the catalog for the creation. It seems to create the stack as user stack
I've tried with account API keys. No change. What should I put in the URL ? The root URL, or an api url (v1 or v2-beta ?)

**Comment by cryptobioz** [comment]
[In our tests](https://github.com/camptocamp/bivac/blob/integration-tests/cattle/tests/01_basic#L82), I removed the option "-s" to let Rancher create a user stack and I've been able to reproduce your behavior.
Could you please try to deploy Bivac as system stack?

**Comment by jeanpommier** [comment]
Hi,
@cryptobioz  OK, you're right. I need to run rancher stack create --start --system bivac with rancher-cli being configured with Account API keys. Environment API keys won't suffice (Rancher would not create the stack as a system stack).
Given that, bivac seems much more eager to work.
Well, I guess Bivac for the C2C catalog won't work out-of-the box, then. At least not from UI.

Bonus questions : isn't Bivac supposed to init the Restic repo if empty ? The logs seem to say otherwise
Is there a forum or something more adapted than the Github issues to ask such questions ?
Thank you

**Comment by cryptobioz** [comment]
> Well, I guess Bivac for the C2C catalog won't work out-of-the box, then. At least not from UI.

You're right, I'll fix that or, at least, add a note to the README.

> Bonus questions : isn't Bivac supposed to init the Restic repo if empty ?

Bivac will create a repo if it doesn't exist but I guess you ask this question because you've seen this kind of log message: `[...] level=debug msg="\nFatal: unable to open config file [...]`.
Before creating a Restic repository, we check if one already exists by trying to list the snapshots.
If the command's exit code is `0`, we consider that there's already a repository, so we skip initialization, otherwise, we create a new one (cf. [engines/restic.go](https://github.com/camptocamp/bivac/blob/master/engines/restic.go#L101-L129))

> Is there a forum or something more adapted than the Github issues to ask such questions ?

Not yet but I guess it's fine to ask questions on Github :)

**Comment by jeanpommier** [comment]
Thanks,
Well, actually, I do get this Fatal error. But in the end, it doesn't init the repo and I end with no backup being done.
The full fatal error message is : 

> 19/11/2018 21:33:13time="2018-11-19T20:33:13Z" level=debug msg="\nFatal: unable to open config file: Stat: stat s3.amazonaws.com/bivac-backups/bk/sk2.pigeosolutions.fr/geonetwork_datadir/config: no such file or directory\nIs there a repository at the following location?\ns3.amazonaws.com/bivac-backups/bk/sk2.pigeosolutions.fr/geonetwork_datadir\nFatal: unable to open config file: Stat: stat s3.amazonaws.com/bivac-backups/bk/sk2.pigeosolutions.fr/geonetwork_datadir/config: no such file or directory\nIs there a repository at the following location?\ns3.amazonaws.com/bivac-backups/bk/sk2.pigeosolutions.fr/geonetwork_datadir" cmd="backup /mnt/geonetwork_datadir/ --host sk2.pigeosolutions.fr --no-cache -r s3.amazonaws.com/bivac-backups/bk/sk2.pigeosolutions.fr/geonetwork_datadir" container=1i2583 volumes="geonetwork_datadir:/mnt/geonetwork_datadir"

Another bonus question : are there some restore procedures built in bivac, or do we have to rely on the backup solution (e.g. restic) for data restoration ?

**Comment by cryptobioz** [comment]
> Well, actually, I do get this Fatal error. But in the end, it doesn't init the repo and I end with no backup being done.

Hmm, interesting... I'll have a look at this.

> Another bonus question : are there some restore procedures built in bivac, or do we have to rely on the backup solution (e.g. restic) for data restoration ?

No, you must use the backup solution to manage and restore your backups.

**Comment by cryptobioz** [comment]
@jeanpommier Is the path `s3.amazonaws.com/bivac-backups/bk` already exists?

**Comment by jeanpommier** [comment]
Hi,
Bivac is supposed to create it if necessary, right ? 
I tried both : existing folder, non-existing folder, no difference.
Of course, the bucket `s3.amazonaws.com/bivac-backups` exists

**Comment by cryptobioz** [comment]
Bivac should create a path if it doesn't exist.
From the log message you posted, we can see that it fails to backup the volume. So, I guess the repository was successfully created? Could you please attach the complete log file (if there's no sensitive data, of course)?

**Comment by jeanpommier** [comment]
Bivac doesn't create the repository. I guess that's where it fails. While exporting the logs, I had a look at the containers and saw the restic container hasn't been started in 2 days, so bivac fails before it even calls restic.
[Here are the logs](http://depots.pigeosolutions.fr/jean/tmp/bivac.logs). I don't think anything sensitive slipped through. FYI, I only whitelisted geonetwork_datadir and geoserver_data for the tests (no need to pay much to amazon while testing)

**Comment by jeanpommier** [comment]
Oh my, you're right ! Silly me. A copy-paste error. My apologies !
It's ok now...
Thanks !
