### ISSUE TITLE
bivac+restic+SFTP ?

### ISSUE THREAD

**Issue by jeanpommier** [camptocamp/bivac#246]
Hi,
Restic supports backup using SFTP, but needs the machine running restic to be configured for connection using ssh keys. That means I need to mount a volume containing an ssh keys config to the restic machine. 
Is there any way to do that using Bivac ? Or are we restricted to password/passkey backup services like AWS S3 ?
Thanks

**Comment by mcanevet** [comment]
@jeanpommier I think this : https://github.com/camptocamp/bivac/pull/232/files#diff-1e4618c6b63a3c30bf6b4fba7673e720R210 should allow to forward Cattle secrets that would be mount on the manager to the workers. And thus, you could store your secret key in a Rancher secret and configure restic to use it.

**Comment by jeanpommier** [comment]
Interesting, yes, thanks
But for passwordless sftp login, I need to configure ssh with ssh keys. Either mount the .ssh forlder with keys at the right place, or configure it in a .ssh/config file. Passing the secrets won't be enough. I suppose I'll have to at least build my own restic docker image...

**Comment by jeanpommier** [comment]
Yes, I get that. But when you have the key in /run/secrets, how do you configure ssh to use it ? This is not default config...

**Comment by jeanpommier** [comment]
Hi,
I did try the sftp.command option. It seems it should work. But apparently, there is an escaping issue. Here's the message I get in the logs (I masked my machines names):
level=debug msg="\ninvalid argument \"sftp.command=\\\"ssh\" for \"-o, --option\" flag: parse error on line 1, column 13: bare \" in non-quoted-field\ninvalid argument \"sftp.command=\\\"ssh\" for \"-o, --option\" flag: parse error on line 1, column 13: bare \" in non-quoted-field" cmd="snapshots --no-cache -r sftp::/bivac_backups/restic/myhost.mydomain/geonetwork_datadir -o sftp.command=\"ssh -i /run/secrets/id_rsa -l root backups.mydomain.fr -s sftp\"" container=1i2837 volumes=

Here is the option I passed:
RESTIC_COMMON_ARGS:-r %B/%P/%V -o sftp.command="ssh -i /run/secrets/id_rsa -l root backups.mydomain.fr -s sftp"
I configured this in cattle directly.

Can you confirm this is a quote escaping issue ? Any idea how to deal with this ?

**Comment by jeanpommier** [comment]
_Some update:_
I found out that official restic docker image doesn't support ssh (code in master does, but the image is not up-to-date) so I built my own image (using restic's master branch, no changes)

I tested directly from inside the restic image (my version) and I can ssh into the backup machine.
My updated restic image is pigeosolutions/restic:latest 

I also tried to use simple quotes in the options line. I get a different error:
> level=debug msg="\nunknown shorthand flag: 'i' in -i\nunknown shorthand flag: 'i' in -i" cmd="init --no-cache -r sftp::/bivac_backups/restic/myhost.fr/geoserver_data -o sftp.command='ssh -i /run/secrets/id_rsa -l root backups.mydomain.fr -s sftp'" container=1i2889 volumes="geoserver_data:/data"

"unknown shorthand flag" seems to be a restic error message, so it seems that when I use simple quotes, restic interprets it to be options destined to himself instead of ssh. That's surprising, since it doesn't behave this way when called in commandline

**Comment by jeanpommier** [comment]
In the meantime, since I have to build my restic image anyway, I'm adding the ssh config in my image. 
@mcanevet , when you said the line allowing to mount the secrets haven't been merged yet, I guess I'll have to also build my bivac image, including your PR, right ?

**Comment by jeanpommier** [comment]
OK, thanks

**Comment by jeanpommier** [comment]
Hi @mcanevet ,
I tried using your modifications to get secrets forwarding, but it seems nothing is forwarded, in my case. I still have following issue

>   level=debug msg="\nsubprocess ssh: Host key verification failed.\nFatal: unable to open repo at sftp:bk.mydomain.fr:/bivac_backups/restic/myhost.mydomain.fr/geoserver_data: unable to start the sftp session, error: EOF\nsubprocess ssh: Host key verification failed.\nFatal: unable to open repo at sftp:bk.mydomain.fr:/bivac_backups/restic/myhost.mydomain.fr/geoserver_data: unable to start the sftp session, error: EOF" cmd="-r sftp:bk.mydomain.fr:/bivac_backups/restic/myhost.mydomain.fr/geoserver_data snapshots --no-cache" container=1i3001 volumes=

If I inspect the restic containers launched by bivac, I don't see any secret, so I guess the restic containers don't receive the secrets.
I tried 2 bivac builds : one applying your PR over bivac master and another one directly from your forward_secret branch. No difference
