### ISSUE TITLE
Duplicity using hard-coded path construction for cleanup(), verify(), and status()

### ISSUE THREAD

**Issue by JimKuhn** [camptocamp/bivac#247]
If I override the environment variables `DUPLICITY_BACKUP_ARGS` and `DUPLICITY_REMOVE_OLDER_THAN_ARGS` to use `%B/%V` instead of `%B/%P/%V`, the code still uses a hard-coded `%B/%P/%V` for `cleanup()`, `verify()`, and `status()`.

This should be refactored so that a single variable/command-line-option controls this format, perhaps into `DUPLICITY_COMMON_ARGS` (similar to restic).

**Comment by ganto** [comment]
@raphink / @cryptobioz : I guess this is not properly fixed. With the latest git HEAD I now get an error:
```
time="2019-01-02T21:30:17Z" level=debug msg="Replacing args, Input: [cleanup --force --extra-clean --name %V --full-if-older-than 15D --allow-source-mismatch --name %V %D %B/%P/%V --s3-use-new-style --ssh-options -oStrictHostKeyChecking=no --ssh-options -oIdentityFile=/etc/bivac-secret/id_ed25519 --no-encryption]"
time="2019-01-02T21:30:17Z" level=debug msg="Replacing args, Output: [cleanup --force --extra-clean --name gitea-data --full-if-older-than 15D --allow-source-mismatch --name gitea-data /data// scp://backup@backup.example.com:/backup/volumes/gitea/gitea-data --s3-use-new-style --ssh-options -oStrictHostKeyChecking=no --ssh-options -oIdentityFile=/etc/bivac-secret/id_ed25519 --no-encryption]"
time="2019-01-02T20:40:27Z" level=debug msg="Usage: \n duplicity [full|incremental] [options] source_dir target_url\n duplicity [restore] [options] source_url target_dir\n duplicity verify [options] source_url [...]\n\nduplicity: error: no such option: --full-if-older-than 15D --allow-source-mismatch --name gitea-data /data// scp://backup@backup.example.com:/backup/volumes/gitea/gitea-data\n"
```
I'm using the default `DUPLICITY_BACKUP_ARGS` and only extended `DUPLICITY_COMMON_ARGS` with my SSH key secret config.

It seems the `--full-if-older-than 15D` from the `DUPLICITY_BACKUP_ARGS` is not valid for the cleanup use case.
