### ISSUE TITLE
Feature request: better (vault) interoperability: read secrets from file(s)

### ISSUE THREAD

**Issue by felixkrohn** [camptocamp/bivac#248]
I plan to use bivac in a openshift/kubernetes container environment with restic. Here I'd like to move the secrets (in my case AWS _ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and RESTIC_PASSWORD) from container environment variables into vault in order not to have them readable to almost everyone in the same namespace. As they're not needed for bivac itself, they could be injected only at invocation of the backup engine containers by the bivac-worker.

It's easy to add a vault-agent sidecar to bivac, have it fetch the secrets, and write them into a shared emptyDir volume. However, it's currentlynot possible to point bivac to use this file. Hence, a commandline option like "--read-env-from=/path/file" would be a useful addition.

Another possibility would be to include a shell binary (busybox?) into the bivac docker image, which would enable users to simply add a wrapper-script that sets environment variables  and then calls bivac , without having to maintain a forked image.

**Comment by raphink** [comment]
I think a `--env-from=/path/to/file` option is acceptable. I'd welcome a PR for that. What's your take @cryptobioz ?
