### ISSUE TITLE
ImagePull returned an error: repository name must be canonical

### ISSUE THREAD

**Issue by ozeranskiy** [camptocamp/bivac#251]
Hello, running the command:
`docker run -v /var/run/docker.sock:/var/run/docker.sock:ro  --rm -ti -e BIVAC_TARGET_URL=<s3> -e AWS_ACCESS_KEY_ID=<key_id> -e AWS_SECRET_ACCESS_KEY=<access_key> -e BIVAC_LOG_LEVEL=debug camptocamp/bivac`
and getting an error:

> ERRO[0013] ImagePull returned an error: repository name must be canonical
...
ERRO[0013] Failed to backup volume backend-api_media-data: failed to backup volume: failed to create a secure repository: after 3 attempts, last error: failed to launch Restic to verify the existence of the repository: failed to pull image: repository name must be canonical

what could be the problem?

**Comment by ozeranskiy** [comment]
I executed the command 
`docker pull restic/restic:latest`
and after bivac started

**Comment by raphink** [comment]
Good that you found how to fix it. I do wonder why it failed though.
