### ISSUE TITLE
unknown flag `aws-access-key-id'

### ISSUE THREAD

**Issue by unclesamwk** [camptocamp/bivac#252]
Hey,

why is the flag unknown?

```
./bivac \
  -o docker \
  -u "s3:https://ams3.digitaloceanspaces.com/dockerspace" \
  --aws-access-key-id=${AWS_ACCESS_KEY_ID} \
  --aws-secret-key-id=${AWS_SECRET_ACCESS_KEY} \
  --restic-password=${RESTIC_PASSWORD}```

**Comment by cryptobioz** [comment]
The arguments like `--aws-access-key-id` or `--aws-secret-key-id` were removed by #228. You must now use the standard AWS environment variables: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

**Comment by unclesamwk** [comment]
thx, please update the example :-)
