### ISSUE TITLE
Helm Chart Not Working

### ISSUE THREAD

**Issue by TaylorChristie** [camptocamp/bivac#254]
I'm trying to test this application with the helm chart on v1.0.0-alpha8 and it isn't able to backup any of my volumes. The documentation for this is sparse so I can't really tell why these backups aren't running. I set the four env variables: BIVAC_TARGET_URL, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, RESTIC_PASSWORD but the output is: 

```
time="2019-02-14T18:30:05Z" level=info msg="Bivac v1.0.0-alpha8-dirty starting backup..."
time="2019-02-14T18:30:05Z" level=info msg="End backup..."
```

On the latest version:
```

Usage:
  bivac [command]
 Available Commands:
  agent       Run Bivac agent
  backup      Backup volumes
  help        Help about any command
  info        Retrive Bivac informations
  manager     Start Bivac backup manager
  restic      Run Restic command on a volume's repository
  volumes     Show volumes
 Flags:
  -b, --blacklist string   Do not backup blacklisted volumes. [BIVAC_VOLUMES_BLACKLIST]
  -h, --help               help for bivac
  -v, --verbose            Enable verbose output [BIVAC_VERBOSE]
  -w, --whitelist string   Only backup whitelisted volumes. [BIVAC_VOLUMES_WHITELIST]
 Use "bivac [command] --help" for more information about a command.
```

Nothing is added to the S3 bucket and all my parameters are fine. Am I missing something?

**Comment by cryptobioz** [comment]
Bivac didn't find any volume to backup.  Are there volumes in the namespace in which you have deployed Bivac?
Could you please set the environment variable `BIVAC_LOG_LEVEL=debug` to make sure we don't miss anything?

Please note that the current Helm chart doesn't support the version 2.0.0.

**Comment by TaylorChristie** [comment]
Okay, I did seperate the name spacing of my apps so I would guess that's the culprit, I'll test to be sure. Is there a way to backup all namespaces?

**Comment by cryptobioz** [comment]
Of course, you can set the environment variable `K8S_ALL_NAMESPACES` to `true`.

**Comment by TaylorChristie** [comment]
Alright, I'll probably submit a pull request with my updated roles and role binding to allow usage of all namespaces, because currently it isn't supported with the current RBAC.

**Comment by cryptobioz** [comment]
You're right, that would be great! PR are always welcome! :-)
