### ISSUE TITLE
Usage for `restic` subcommand can be improved

### ISSUE THREAD

**Issue by kumy** [camptocamp/bivac#257]
The actual `Usage` for the `restic` subcommand is quite incomplete, see:

```
# bivac restic --volume test restore 3dae715d --target /tmp/test2
Error: unknown flag: --target
Usage:
  bivac restic --volume [VOLUME_ID] [COMMAND] [flags]
[…]
```
Adding `--` to separate flags for `restic` help running the command.

```
root@330114bd3e81:/# bivac restic --volume test -- restore  3dae715d --target /tmp/test2
restoring <Snapshot 3dae715d of [/var/lib/docker/volumes/test/_data] at 2019-02-25 16:31:44.280051982 +0000 UTC by @heron.xxx> to /tmp/test2
```

IMHO, usage should look like `bivac restic --volume [VOLUME_ID] [COMMAND] [flags] -- [RESTIC_FLAGS]`

**Comment by cryptobioz** [comment]
I updated the usage message for the `restic` subcommand : https://github.com/camptocamp/bivac/commit/27a46157e8af564e3aefe06f39f47f673f0e3dbf

**Comment by kumy** [comment]
@cryptobioz That was my first idea for a patch, but I was afraid to see the global `[flags]` at the end of the line. I suspect the result now to be `bivac restic --volume [VOLUME_ID] [COMMAND] -- [RESTIC_FLAGS] [flags]`, which seems wrong. What do you think?
