### ISSUE TITLE
Use 'restic stats' instead of 'restic check' to determine if repo exists

### ISSUE THREAD

**Issue by mcanevet** [camptocamp/bivac#260]

**Comment by Cobrijani** [comment]
https://restic.readthedocs.io/en/latest/075_scripting.html#check-if-a-repository-is-already-initialized

What about restic snapshots?

**Comment by cryptobioz** [comment]
This is an old issue but you're right @Cobrijani, we're already using `snapshots` to check the existence of a repository (cf. https://github.com/camptocamp/bivac/blob/master/internal/engine/engine.go#L116).
