### ISSUE TITLE
500 error when backing up kubernetes volume

### ISSUE THREAD

**Issue by codejamninja** [camptocamp/bivac#271]
I get the following error when trying to backup a kubernetes volume.

```
ERRO[0000] failed to backup volume: failed to connect to the remote Volback instance: received wrong status code from the Volback instance: [500] 500 - Internal server error
```

I know this is a terrible issue to file because I'm not providing much information, however, this is because I cannot figure out how to get a stack trace. So really if you could help me figure out how to get more details from the application that would be great.

**Comment by codejamninja** [comment]
I was able to capture the full request and response using tcpflow, but I still do not know how to get a stack trace. I have verbose logging enabled and it doesn't really tell me much.

_request_
```
127.000.000.001.50738-127.000.000.001.08182: POST /backup/2eea802c-45d7-11e9-ab64-06386126fbee?force=falseHTTP/1.1
Host: 127.0.0.1:8182
User-Agent: Go-http-client/1.1
Content-Length: 0
Authorization: Bearer test
Accept-Encoding: gzip
```

_response_
```
127.000.000.001.08182-127.000.000.001.50738: HTTP/1.1 500 Internal Server Error
Date: Fri, 22 Mar 2019 08:53:25 GMT
Content-Length: 27
Content-Type: text/plain; charset=utf-8

500 - Internal server error
```

**Comment by cryptobioz** [comment]
I'm sorry but I'll not help you to debug _your_ project.

**Comment by codejamninja** [comment]
No problem. I’ll submit a pull request when I track down the bug.
