### ISSUE TITLE
Rancher 2 compatible helm chart

### ISSUE THREAD

**Issue by clayrisser** [camptocamp/bivac#274]
It would be nice if there was a rancher 2 compatible helm chart for bivac

https://rancher.com
https://helm.sh

**Comment by mcanevet** [comment]
Does Rancher 2 requires specify Helm Chart, or a standard Helm Chart could run on it?

**Comment by codejamninja** [comment]
Yes a standard helm chart can run this. A rancher 2 helm chart simply provides a questions.yaml file in addition to the regular helm files.
