### ISSUE TITLE
Compare last backup start time instead of end time to decide if backup is needed

### ISSUE THREAD

**Issue by mcanevet** [camptocamp/bivac#284]
Currently we are comparing with the last backup date, which I guess matches the end time of the last backup, when deciding whether or not we have to backup again : https://github.com/camptocamp/bivac/blob/86089277b68fa8a5c7a3813fef1d01203e76176e/internal/manager/manager.go#L152.
I think we should compare with the last backup start time to really backup every 24 hours and prevent false positive in monitoring on huge volumes.
For example, if we have a huge volume that takes 4 hours to backup ; on day 0, the volume is backed up from 8am to 12am, then on day 1 it will be backed up from 12am to 4pm. If we check if backup is older than 24 hours, we'll have an alert from 12am to 4pm on day 1. If we start the backup 24 hours after the beginning of the previous backup, then on day 1 the backup would start at 8am and end around 12am, thus it would not fire any alert (or maybe just for a few minutes if the backup is a bit longer than the day before).

**Comment by mcanevet** [comment]
@cryptobioz isn't this done?

**Comment by cryptobioz** [comment]
Yes, it has been fixed by fe1b0387.
