### ISSUE TITLE
More advanced whitelisting and blacklisting for Kubernetes

### ISSUE THREAD

**Issue by codejamninja** [camptocamp/bivac#292]
Would be nice to be able to whitelist and blacklist using Kubernetes annotations.

Would also be great if I could whitelist/blacklist an entire namespace.

**Comment by codejamninja** [comment]
For backwards compatibility, it should backup all kubernetes volumes except the ones annotated `bivac.backup: 'false'`.

However a whitelist mode would also be nice. `BIVAC_WHITELIST_ANNOTATIONS=true` would basically reverse the annotation logic, so no volumes are backed up except the ones annotated `bivac.backup: 'true'`.

**Comment by mcanevet** [comment]
@codejamninja I will close this as your PR has been merged.
Feel free to reopen if you still miss something.
