### ISSUE TITLE
BIVAC_REMOTE_ADDRESS not documented

### ISSUE THREAD

**Issue by Vampouille** [camptocamp/bivac#300]
There is 2 options regarding communication from client to manager:
```
--server.address string     Address to bind on. [BIVAC_SERVER_ADDRESS] (default "0.0.0.0:8182")
--log.server string     Manager's API address that will receive logs from agents. [BIVAC_LOG_SERVER]
```
There is also an option that is not documented. Command line says : 
```
--remote.address string     Address of the remote Bivac server. [BIVAC_REMOTE_ADDRESS] (default "http://127.0.0.1:8182")
```

It would be better to have only one option/env var to configure remote manager address.

**Comment by cryptobioz** [comment]
For now, I'll add documentation to explain those different variables and their use.
Even if I agree that we should simplify this, I fear that merging them could lead to annoying side-effects.
