### ISSUE TITLE
Allow Backup to Azure

### ISSUE THREAD

**Issue by dhilgarth** [camptocamp/bivac#301]
It should be possible to backup to Azure.
Both Duplicity and restic support this out of the box - is there any reason for not supporting it?

**Comment by mcanevet** [comment]
it should be supported out of the box. I never tried, but I guess you just have to pass `AZURE_ACCOUNT_NAME` and `AZURE_ACCOUNT_KEY` and set restic repo to something like `azure:foo:/`.

**Comment by dhilgarth** [comment]
I can confirm that it works. Using `azure://foo` - which would have been correct for duplicity - doesn't work but it will fail silently without any error message.

**Comment by mcanevet** [comment]
OK, great to know that it works for Azure.
I remove all references to Duplicity and RClone on the website to make it clear that we only support Restic now.

**Comment by dhilgarth** [comment]
What about the fact that there is no info about the failed upload if the url is incorrect?

**Comment by mcanevet** [comment]
Could you open another issue for that?
