### ISSUE TITLE
Ignore vendor folder

### ISSUE THREAD

**Issue by codejamninja** [camptocamp/bivac#303]
I do not believe the `/vendor` folder should be in the git history.

**Comment by cryptobioz** [comment]
As you may know, the Golang dependencies management is quite a mess. As we cannot still fully rely on the Go modules (or other dependency management tools), we decided to add a `vendor` directory to keep all the deps locally.
Even if I agree with you that it isn't great to commit this, it's a common practice in the Golang community and, from my experience, I can tell it can be very, very useful. :)
