### ISSUE TITLE
Any plans to support other backends than s3 ? 

### ISSUE THREAD

**Issue by lukasmrtvy** [camptocamp/bivac#319]
Any plans to support other backends than s3 ? 
Restic supports a lot of backends, even rclone backend(https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone), which can provide a lot of other backends https://rclone.org/overview/

**Comment by mcanevet** [comment]
@lukasmrtvy Bivac supports all backend that Restic support. You just have to pass the proper environment variables.

**Comment by lukasmrtvy** [comment]
reference: https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables
