### ISSUE TITLE
Add support for MS SQL Server

### ISSUE THREAD

**Issue by dhilgarth** [camptocamp/bivac#320]
MS SQL Server runs on Linux and in Docker Containers since version 2017.
Many enterprises are using it, especially ones coming from the Microsoft world and building applications in C#.

It would be great if bivac would support it similar to how it supports other DBMS.

**Comment by raphink** [comment]
The whole logic for providers is in `providers-config.default.toml`. Feel free to provide a PR to add MS SQL support in this file.
