### ISSUE TITLE
Restic "rest server" backend seemingly not working

### ISSUE THREAD

**Issue by arthurtemple** [camptocamp/bivac#330]
Hello,

I am having difficulty using bivac manager alongside restic's rest server, one of the backends supported by restic.
The agent receives a 404 on repo creation and fails subsequently.

Here is a docker-compose.yml to illustrate (example given for a MacOS host):

```
version: '2'

volumes:
  stuff: {}

services:
  restic-server:
    image: restic/rest-server:0.9.7
    volumes:
      - /path/to/my/repos:/data
    environment:
      DISABLE_AUTHENTICATION: 1
      OPTIONS: "--debug"
    ports:
      - 8000:8000
  bivac:
    image: camptocamp/bivac:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      BIVAC_TARGET_URL: rest:http://docker.for.mac.localhost:8000
    command: ["manager"]
    ports:
      - 8182:8182
```

Intercepting logs from bivac agent will give this:
```
2019-12-10T14:36:04.902338500Z init: Fatal: create repository at rest:http://docker.for.mac.localhost:8000/docker-desktop/myproject_stuff failed: Fatal: server response unexpected: 404 Not Found (404 )
2019-12-10T14:36:04.902405300Z
2019-12-10T14:36:04.902429000Z
2019-12-10T14:36:04.995644500Z backup: Fatal: unable to open config file: unexpected HTTP response (500): 500 Internal Server Error
2019-12-10T14:36:04.995669400Z Is there a repository at the following location?
...
2019-12-10T14:36:25.190385300Z 2019-12-10T14:36:35.196138900Z time=“2019-12-10T14:36:35Z” level=info msg=“Response from API: Unauthorized”
```
As one could expect, the repository is not created on rest-server.

Indeed, launching bivac agent manually will give same result:
`docker run --rm -it restic/restic:latest backup -p /path/to/my/folder -r rest:http://docker.for.mac.localhost:8000/docker-desktop/myproject_stuff --host docker-desktop`

However, launching bivac agent *without the /docker-desktop/ prefix* will work as expected and create a repository on the server:

I naively suppose that the url path in queries to restic's rest-server should not include the "volume path" (here "docker-desktop"), but this is of course only from a quick ignorant glance.

Any advice on this matter?

Thanks to all and congrats for this very nice project!

**Comment by ygbillet** [comment]
Hi,

It seems restic rest server cannot handle more than 1 subdirectory.


Is there a way to make it works with Bivac ? (i didn't find the options to remove the "host prefix")

**Comment by cryptobioz** [comment]
Hello,

Indeed, the Restic Rest Server isn't able to handle multiple subdirectories yet. However, a PR has been opened to add this feature among others: https://github.com/restic/rest-server/pull/112

We could also add an option to Bivac in order to format the "host prefix" as you said. This could be great but we will not have time to implement it. 

Please feel free to open a PR if you want, we would be pleased to review it :)

**Comment by Akruidenberg** [comment]
I have the same problem. Bacause the prefix, i cant make any backuo. Other backup containers with restic are working fine.
