### ISSUE TITLE
Document how to determine if a lock is "legit"

### ISSUE THREAD

**Issue by soullivaneuh** [camptocamp/bivac#332]
According to your wiki page: https://github.com/camptocamp/bivac/wiki/Usage#my-backup-failed-because-the-remote-repository-is-locked

> The first thing to do is to check the date and the user who created the lock. From these informations, you should be able to determine if the lock is "legit"

It would be great to have some good indication of how to check this, or maybe a bivac feature itself to provide this information.

**Comment by cryptobioz** [comment]
Hi, thanks for this feedback.

Bivac uses Restic to manage all the backup part. The lock you might find in your repositories is created by Restic in various operations that require data manipulation. You can find more information about this in the Restic documentation: [https://restic.readthedocs.io/en/latest/100_references.html#locks](https://restic.readthedocs.io/en/latest/100_references.html#locks)

In the context of Bivac, I'd say that it's pretty easy to know if a lock is "legit" (aka a Restic process is manipulating data) or if it is only a remnant from a interrupted backup. In most of cases, if none of these assertions are true, it means the lock can be removed:

- Is Bivac backing up a volume or restoring one?
- Is an administrator doing a manual operation on the Restic repository?

The lock by itself also contains useful information like the hostname, the user id or the date that can help you to determine whether it is safe to remove or not.
