### ISSUE TITLE
How to configure what volume to backup?

### ISSUE THREAD

**Issue by soullivaneuh** [camptocamp/bivac#334]
I did a fresh install of bivac on my computer following the [docker manual](https://github.com/camptocamp/bivac/wiki/Installation#docker).

It is up and I can run `bivac volumes`. I have a list or not backed up volume.

I don't want to backup all volume I found, only some. How can I configure that?

AFAIK, there is nothing about that on the documentation.

**Comment by soullivaneuh** [comment]
Maybe https://github.com/camptocamp/bivac/issues/331 can handle my case.

**Comment by cryptobioz** [comment]
There are two ways to filter the volumes: the whitelist and the blacklist.

By using the environment variable `BIVAC_VOLUMES_WHITELIST`, you will be able to select the volumes to backup. For example, with `BIVAC_VOLUMES_WHITELIST=foo,bar`, Bivac will only backup the volumes `foo` and `bar`.

By using the environment variable `BIVAC_VOLUMES_BLACKLIST`, you will be able to select the volumes you don't want to backup. For example, with `BIVAC_VOLUMES_BLACKLIST=foo,bar`, Bivac will backup all the volumes except `foo` and `bar`.

As you can see, the only filters available are based on the volumes name.

BTW, thanks for the feedback, I'll update the documentation.

**Comment by soullivaneuh** [comment]
Thanks for the explanation, I'll try this.

> BTW, thanks for the feedback, I'll update the documentation.

You are welcome. I keep this issue open until the documentation is updated. :+1:
