### ISSUE TITLE
k8s: bivac try to use a serviceaccount that does not exists

### ISSUE THREAD

**Issue by Vampouille** [camptocamp/bivac#336]
When the manager launch the agent it use KUBERNETES_AGENT_SERVICE_ACCOUNT env var to attach the service account to the agent. The agent does not need a specific service account. So I think we do not need this env var.

**Comment by felixkrohn** [comment]
It's not necessary, but helpful to have a separate sa in order to attach custom RBAC, for example to (only) allow access to PVCs of all namespaces.
