### ISSUE TITLE
Restore a backup from another host

### ISSUE THREAD

**Issue by dhilgarth** [camptocamp/bivac#339]
I am trying to migrate my containers to another machine and want to use my bivac backups for that purpose.  
The old machine is named linux-host, the new one container-host.  
Bivac is configured to backup to an Azure blob storage, which seems to be working fine.

The problem now is that bivac is creating a folder with the host name and below that it creates the folders for the volumes it backs up. And it uses the same logic during restore to locate the files of the backup.

So: Backup was running on `linux-host` -> All backup files are in a folder structure below `\linux-host\`.  
Restore is running on `container-host` -> Bivac is looking for the files in `\container-host\`, which obviously doesn't exist.

So, how to tell the restore to use another host name to locate the backups?

**Comment by cryptobioz** [comment]
Indeed, we need to patch this feature. I'll work on this as soon as possible.

**Comment by dhilgarth** [comment]
Awesome!

**Comment by dhilgarth** [comment]
Any ETA?

**Comment by cryptobioz** [comment]
I'm currently working on this but it requires to redesign a part of the restoration process. I can't give a realistic ETA but I'll try to keep you inform of progress.

**Comment by dhilgarth** [comment]
Great, thanks

**Comment by prasenforu** [comment]
This scenario is similar in Kubernetes, where ID are coming some unique number .. it may change

![image](https://user-images.githubusercontent.com/19322497/80163879-1ee49500-85f5-11ea-8c2e-27db7726e182.png)

looking for command for restoration when id will change.

**Comment by dhilgarth** [comment]
You wanted to keep us informed of the progress. Can you please give an update? I am holding off on the migration of my containers so far because of this, but it now becomes critical.

**Comment by dhilgarth** [comment]
I have since simply copied the backups to a folder in my Azure storage that is named after the new host. This allowed me to restore.

**Comment by daniel-illi** [comment]
@cryptobioz do you still plan to finish this patch or is the automatic 'wontfix' label final?
