### ISSUE TITLE
Keep more than 15 backups

### ISSUE THREAD

**Issue by LongJeongS** [camptocamp/bivac#341]
Is it possible to change the policy of only keeping the latest 15 backups?  I see that it gets set when backing up the volumes 
```
forget          [0] Applying Policy: keep the last 15 daily snapshots
                        snapshots for (host [testing]):
```

**Comment by LongJeongS** [comment]
Looks like restic itself doesnt have any default policies: https://forum.restic.net/t/default-retention-policy/2492, so its enforced by bivac somewhere?

**Comment by cryptobioz** [comment]
Indeed, Bivac uses the following forget policy by default: `--group-by host --keep-daily 15 --prune`.

https://github.com/camptocamp/bivac/blob/680f2ddd05df27fca8d517a7075212731f8fe5e6/cmd/manager/manager.go#L91

It can be overwritten by using the command line argument `--restic.forget.args` or the environment variable `RESTIC_FORGET_ARGS`.
You can set the forget policy that you want but I'd recommend you to keep at least the two options `--group-by host` and ` --prune`.

**Comment by LongJeongS** [comment]
Thanks! That did the trick :)
