### ISSUE TITLE
Looking for local setup

### ISSUE THREAD

**Issue by prasenforu** [camptocamp/bivac#345]
Following as below, 

![image](https://user-images.githubusercontent.com/19322497/80164824-af23d980-85f7-11ea-937e-84852cd37516.png)

```
bivac   --u s3:http://minio-local:9000/local-backups   --aws-access-key-id=admin   --aws-secret-key-id=admin
Error: unknown flag: --u
```

**Comment by mcanevet** [comment]
Can you try with a single `-` as in the documentation?

**Comment by prasenforu** [comment]
basically ```u``` option not available.

![image](https://user-images.githubusercontent.com/19322497/80178774-ad204180-861c-11ea-91d8-30f10c12d834.png)

**Comment by pbajno** [comment]
@prasenforu Does it work now?

**Comment by cryptobioz** [comment]
The website isn't up to date. I suggest you to try with the following command:

```
docker run -d --name bivac -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -e AWS_ACCESS_KEY_ID=XXXX \
  -e AWS_SECRET_ACCESS_KEY=XXXXXX \
  -e BIVAC_TARGET_URL=s3:my-bucket \
  -e RESTIC_PASSWORD=foo \
  -e BIVAC_SERVER_PSK=toto \
  -p 8182:8182 \
ghcr.io/camptocamp/bivac:2 manager
```
