### ISSUE TITLE
MySQL backup: all.sql has no line breaks

### ISSUE THREAD

**Issue by dhilgarth** [camptocamp/bivac#348]
I have used bivac to backup a mysql database volume.
The resulting `all.sql` doesn't have a single linebreak and therefore treats the whole content as a comment.

**Comment by droidrider** [comment]
Hi,

I have the same issue. It is impossible to import the sql dump in this state.

**Comment by cryptobioz** [comment]
I haven't been able to reproduce your issue, however I found a mistake in the providers-config for MySQL : 481ca51d47d70290936eb2f0dc0c5a76e32036f1

Could please try the latest build of Bivac ([camptocamp/bivac:latest](https://hub.docker.com/layers/camptocamp/bivac/latest/images/sha256-3982c5af228aa8294ca09f8613aae070c2c543755daa8e45ee21e9fb769cfc14?context=explore)) and tell me if it fixes your problem?

Could you also share with us the version of your MySQL instance? As Bivac is using the locally installed `mysqldump` binary, your issue might come from an unsupported version of it.

**Comment by foucaude** [comment]
Same problem here. *.db file is empty.
