### ISSUE TITLE
please add arm64 support

### ISSUE THREAD

**Issue by unclesamwk** [camptocamp/bivac#356]
Hey,

please add arm64 support for very nice bivac ...
```
Pulling bivac ... pulling from camptocamp/bivac

ERROR: for bivac  no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

greetings
Sam

**Comment by raphink** [comment]
@cryptobioz would you like to switch to goreleaser maybe?

**Comment by cryptobioz** [comment]
@unclesamwk Thanks for your request, I added the support of ARM64.

@raphink Yeah, I should have a look at it.
