### ISSUE TITLE
current state of local filsystem backup

### ISSUE THREAD

**Issue by Akruidenberg** [camptocamp/bivac#361]
What is the current state of backing up to a local filesystem? Like /backup? I really like the idea of Bivac, but its really useless without such option. 

Is this function implemented, and how to setup this with envs?

Thanks in advance!

**Comment by cryptobioz** [comment]
There is no proper way to backup your data to a local filesystem.
However, I'm not sure to understand why you would need to do that... Could you please provide some information regarding your environment and your constraints as I could give you a better answer?

**Comment by Akruidenberg** [comment]
Im would like to backup to a local usb drive, and another to another house. When searching here between the issues, a rest server is a perfect solution to solve a local backup.

However. When setting up a docker container with rest-server, it won't connect. Every time I see internal server 500 errors. Setting up resticker in docker container is working fine. Looks like a bug in bivac.

**Comment by Akruidenberg** [comment]
#330
