### ISSUE TITLE
Which is the official and maintained docker repo?

### ISSUE THREAD

**Issue by alexander-zimmermann** [camptocamp/bivac#367]
Hey folks,

it seems that you switch from docker hub to ghcr.io. Correct? At least the version on docker hub is quite old. Can you tell me what repo you maintain? If you like I can fix the docu/wiki if necessary.

Alex

**Comment by jedimonkey** [comment]
With over a year and no releases and most issues closed automatically, I'm going to say this project is abandoned. :-/
