### ISSUE TITLE
Cannot use scp or sftp with ssh keys

### ISSUE THREAD

**Issue by Pamplemousse** [camptocamp/bivac#78]
First of all, thank you for this really promising tool.

I am struggling a bit here as I do not use AWS and I would like to see Conplicity (which I run in a container) send the backup over ssh.

Problem is: there is currently no way to pass authentication keys all the way down to the Duplicity container, hence a `permission denied` is all I can get so far.

I am really happy to help implementing this, but TBH, I do not really now how to do it or where to start.

**Comment by mcanevet** [comment]
We are currently using:
```
DUPLICITY_TARGET_URL=pexpect+sftp://<user>:<password>@<server>/<target_path>
```
If you want to use private key authentication I think we have to store the private key in an environment variable and dump it into `$HOME/.ssh/id_rsa` in `camptocamp/duplicity`'s entry point.

**Comment by Pamplemousse** [comment]
What's your opinion on using volumes here?

IMO, ```camptocamp/duplicity``` docker image does not need to be touched, everything can be done in this project:

  * ```docker run camptocamp/conplicity``` would need to add the ssh key from the host inside the container, wherever we want (say ```/ssh```)
  * the ```LaunchDuplicity``` function (in the code) would mount this ```/ssh``` into the Duplicity container into ```/root/.ssh/```

**Comment by mcanevet** [comment]
Well it could work in some use case. In our case we don't generally store anything on the host that runs docker containers, so we don't have the ssh key on it. That's why I was suggesting using an environment variable to store the private key (or maybe something like vault).

**Comment by Pamplemousse** [comment]
I am not a fan of passing the key via an environment variable, especially because of logging.

The more I look at this problem, the more I am convinced that we will need to update the code to pass extra options to the Duplicity container... Or rebuild the Duplicity image every time Conplicity runs which is not really ideal.

Another difficulty will be the rights associated with the keys when passed to the container: the file will have the uid of the key file's owner on the host, and ```sshd``` being pretty strict towards the ownership and permissions of these, it will not run without more customization (had a similar problem before: https://github.com/William-Yeh/docker-ansible/issues/14#issue-151796386).

Maybe just pass the ```ssh_agent``` to keep it simple?

**Comment by mcanevet** [comment]
Passing `ssh_agent` will not work for our use case either (we are using rancher)

**Comment by auzias** [comment]
I met the same problem.

@mcanevet is there any way around Docker volume that would offer an elegant solution?

I know you do not use this as your ssh-key are not on the host but since 22 days ago, maybe something came up.

**Comment by raphink** [comment]
@auzias we do not use SSH at all, only object storage (AWS S3 or Swift). That said, how would you like an `--extra-mounts` option with a list of volumes to mount in the engine container?

```
$ conplicity --extra-mounts="sshkeys:/root/.ssh,/etc/ssh:/etc/ssh"
```

which would mount two volumes:

* the `sshkeys` volume with your SSH keys into `/root/.ssh` of the duplicity (or rclone) container
* the `/etc/ssh` volume from the host into `/etc/ssh` of the container (for `known_hosts` for example)


Would that fit your need?

**Comment by Pamplemousse** [comment]
This seems to be a nice way to go and would perfectly fit our needs.

I even prefer to pass a specific key as you proposed rather than the agent (more flexible about the client we run it from).

**Comment by raphink** [comment]
OK, that seems like a good way to go then. If any of you wants to prepare a PR, I'll be happy to review it.

**Comment by mcanevet** [comment]
I think we can address this by storing the private key in a secret, and mount the secret in the workers. I would work at least when using rancher or kubernetes as orchestrator.

**Comment by mcanevet** [comment]
I was thinking about it again. I think the most flexible solution would be, for Kubernetes, to read the manager's pod's volumes and volumeMounts, and propagate it to the worker, if it's kind of:
- RWX PersistentVolumeClaim, so that we can backup to a shared volume,
- ConfigMap, so that we can support complex/custom engine configuration,
- Secret, so that we can support mounting secret as file (like SSH private key for example).
Moreover, we should also propagate all manager's pod's environment variable to the worker so that we can fine tuning the engine and expose API keys from secrets.

**Comment by mcanevet** [comment]
@cryptobioz do you have any idea how we can inspect the current pod using the go bindings to retrieve its environment variables, volumes and volumeMounts?

**Comment by mcanevet** [comment]
@Pamplemousse this is now possible with latest. All volumes passed to the manager will be forwarded to workers, so all you have to do is to mount your private key in a volume.
Feel free to reopen if you still have an issue with this.
